config/routes.rb
Spree::Core::Engine.routes.draw do
  # URL for start connection with WebpayWS
  scope '/oneclick_mall' do
    get  'pay', to: 'oneclick_mall_payment#pay', as:  :oneclick_mall_pay

    get  'subscription', to: 'oneclick_mall_subscription#subscription', as:  :oneclick_mall_subscription

    post 'subscribe', to: 'oneclick_mall_subscription#subscribe', as:  :oneclick_mall_subscribe

    post 'subscribe_confirmation', to: 'oneclick_mall_subscription#subscribe_confirmation', as:  :oneclick_mall_subscribe_confirmation

    get  'subscribe_success', to: 'oneclick_mall_subscription#subscribe_success', as:  :oneclick_mall_subscribe_success

    get  'subscribe_failure', to: 'oneclick_mall_subscription#subscribe_failure', as:  :oneclick_mall_subscribe_failure

    get  'm_subscribe_success', to: 'oneclick_mall_subscription#m_subscribe_success', as:  :oneclick_mall_m_subscribe_success

    get  'm_subscribe_failure', to: 'oneclick_mall_subscription#m_subscribe_failure', as:  :oneclick_mall_m_subscribe_failure

    get  'unsubscription', to: 'oneclick_mall_subscription#unsubscription', as:  :oneclick_mall_unsubscription

    get 'unsubscribe', to: 'oneclick_mall_subscription#unsubscribe', as:  :oneclick_mall_unsubscribe

    get 'success', to: 'oneclick_mall_payment#success',  as:  :oneclick_mall_success

    get 'failure', to: 'oneclick_mall_payment#failure',  as:  :oneclick_mall_failure

    get 'm_success', to: 'oneclick_mall_payment#m_success',  as:  :oneclick_mall_m_success

    get 'm_failure', to: 'oneclick_mall_payment#m_failure',  as:  :oneclick_mall_m_failure
  end

  namespace :api, path: 'api' do
    namespace :v2 do
      namespace :storefront do
        namespace :account do
          post 'subscribe', to: 'oneclick_mall_subscription#subscribe', as: :oneclick_mall_m_subscribe
          get 'unsubscribe', to: 'oneclick_mall_subscription#unsubscribe', as: :oneclick_mall_m_unsubscribe
          get 'pay', to: 'oneclick_mall_payment#pay_with_webpay_oneclick_mall', as: :oneclick_mall_m_pay
          get 'user', to: 'oneclick_mall_users#index', as:  :oneclick_mall_user
          get 'v2pay', to: 'oneclick_mall_v2_payment#pay_with_webpay_oneclick_mall', as: :oneclick_mall_v2_m_pay
          get 'order_status', to: 'oneclick_mall_v2_payment#order_status', as: :oneclick_mall_m_order_status
        end
      end
    end
  end
end

app/models/spree/oneclick_notification.rb
module Spree
  class OneclickNotification < Spree::Base
    belongs_to :order, class_name: 'Spree::Order'
    belongs_to :payment, class_name: 'Spree::Payment'
  end
end

app/models/spree/user_decorator.rb
module Spree::UserDecorator
  def self.prepended(base)
    base.has_one :webpay_oneclick_mall_user, class_name: 'Tbk::WebpayOneclickMall::User',  foreign_key: :user_id
  end
end

Spree::User.prepend Spree::UserDecorator

app/controllers/spree/api/v2/storefront/account/oneclick_mall_payment_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        module Account
          class OneclickMallPaymentController < ::Spree::Api::V2::ResourceController
            include Spree::Api::V2::Storefront::OrderConcern
            before_action :ensure_order

            def pay_with_webpay_oneclick_mall
              @order = spree_current_order
              unless @order.present?
                render json: { success: false, message: 'no order found' }, state: 404
                return
              end
              payment_method = Spree::PaymentMethod.where(type: 'Spree::PaymentMethod::WebpayOneclickMall').first
              oneclick_create_payment(payment_method)

              if pay(payment_method)
                render json: { success: true, message: @response }
              else
                render json: { success: false, message: @response }
              end

            rescue StandardError => e
              oneclick_error(e)
            end

            def oneclick_create_payment(payment_method)
              @payment = @order.payments.build(payment_method_id: payment_method.id, amount: @order.total, state: 'checkout')

              unless @payment.save
                raise 'cant create payment ' + @payment.errors.full_messages.join("\n")
              end

              unless @payment.pend!
                raise 'cant create pend ' + @payment.errors.full_messages.join("\n")
              end
            end

            def pay(payment_method)
              unless @order.user && @order.user.webpay_oneclick_mall_user && @order.user.webpay_oneclick_mall_user.subscribed?
                redirect_to oneclick_mall_subscription_path and return
              end

              provider            = payment_method.provider.new
              amount              = @order.webpay_amount
              user                = @order.user
              oneclick_user       = user.webpay_oneclick_mall_user
              shares_number       = 1
              oneclick_authotize  = provider.authorize(user.id,
                oneclick_user.tbk_user,
                @order.number,
                @order.webpay_amount,
                shares_number,
                @payment.number)

              @response = oneclick_authotize.details

              if oneclick_authotize.details.first['status'] == 'AUTHORIZED' && oneclick_authotize.details.first['response_code'].zero?
                @payment.complete!
                @order.skip_stock_validation = true
                @order.next! unless @order.state == "completed"

                return true
              else
                @payment.failure!
                return false
              end
            end

            def oneclick_error(e = nil)
              render json: { success: false, message: "oneclick error #{e.try(:message)}" }
              return
            end
          end
        end
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/account/oneclick_mall_subscription_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        module Account
          class OneclickMallSubscriptionController < ::Spree::Api::V2::ResourceController
            before_action :require_spree_current_user

            def subscribe
              user = spree_current_user

              if user.blank?
                raise(ActiveRecord::RecordNotFound)
              end

              username = user.id
              email = user.email
              init_subscription = Tbk::WebpayOneclickMall::Subscription.new.init_inscription(username,
                email,
                oneclick_mall_subscribe_confirmation_url)


              if init_subscription.token.present? && init_subscription.url_webpay.present?
                if user.webpay_oneclick_mall_user
                  user.webpay_oneclick_mall_user.update(token: init_subscription.token, mobile: true, subscribed: false)
                else
                  user.create_webpay_oneclick_mall_user(token: init_subscription.token, mobile: true)
                end
                args = { TBK_TOKEN: init_subscription.token }

                render json: { redirect_url: "#{init_subscription.url_webpay}?#{args.to_query}" }
              end
            end

            def unsubscribe
              if spree_current_user
                webpay_oneclick_mall_user = spree_current_user.webpay_oneclick_mall_user
                webpay_oneclick_mall_user.destroy
                unsubscribe = Tbk::WebpayOneclickMall::Subscription.new.remove_inscription(spree_current_user.id, webpay_oneclick_mall_user.tbk_user)
                render json: { success: true }
              else
                render json: { success: false, message: 'no user' }
              end
            rescue
              render json: { success: false, message: 'unexpected error' }
            end
          end
        end
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/account/oneclick_mall_users_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        module Account
          class OneclickMallUsersController < ::Spree::Api::V2::ResourceController
            before_action :require_spree_current_user

            def index
              webpay_oneclick_mall_user = spree_current_user.webpay_oneclick_mall_user
              render json: {
                subscribed: webpay_oneclick_mall_user.subscribed,
                oneclick_auth_code: webpay_oneclick_mall_user.authorization_code,
                oneclick_card_type: webpay_oneclick_mall_user.card_type,
                oneclick_card_number: webpay_oneclick_mall_user.card_number,
                oneclick_updated_at: webpay_oneclick_mall_user.created_at
              }, status: 200
            rescue
              render json: { success: false, message: 'no user' }, status: 400
            end
          end
        end
      end
    end
  end
end

app/controllers/spree/api/v2/storefront/account/oneclick_mall_v2_payment_controller.rb
module Spree
  module Api
    module V2
      module Storefront
        module Account
          class OneclickMallV2PaymentController < ::Spree::Api::V2::ResourceController
            include Spree::Api::V2::Storefront::OrderConcern
            before_action :ensure_order, except: [:order_status]

            def pay_with_webpay_oneclick_mall
              @order = spree_current_order
              unless @order.present?
                render json: { success: false, message: 'no order found' }, state: 404
                return
              end
              payment_method = Spree::PaymentMethod.where(type: 'Spree::PaymentMethod::WebpayOneclickMall').first
              oneclick_create_payment(payment_method)

              if pay(payment_method)
                render json: { success: true, message: @response }
              else
                render json: { success: false, message: @response }
              end

            rescue StandardError => e
              oneclick_error(e)
            end

            def order_status
              if params[:order_number].blank?
                render json: { success: false, message: 'no order found' }, state: 404
                return
              end
              @order = Spree::Order.find_by(number: params[:order_number])

              if @order.blank?
                render json: { success: false, message: 'no order found' }, state: 404
                return
              end

              res = @order.completed_at.present? ? 'complete' : 'pending'

              render json: { success: true, message: res }
            end

            def oneclick_create_payment(payment_method)
              @payment = @order.payments.build(payment_method_id: payment_method.id, amount: @order.total, state: 'checkout')

              unless @payment.save
                raise 'cant create payment ' + @payment.errors.full_messages.join("\n")
              end

              unless @payment.pend!
                raise 'cant create pend ' + @payment.errors.full_messages.join("\n")
              end
            end

            def pay(payment_method)
              unless @order.user && @order.user.webpay_oneclick_mall_user && @order.user.webpay_oneclick_mall_user.subscribed?
                redirect_to oneclick_mall_subscription_path and return
              end

              provider            = payment_method.provider.new
              amount              = @order.webpay_amount
              user                = @order.user
              oneclick_user       = user.webpay_oneclick_mall_user
              shares_number       = 1
              oneclick_authotize  = provider.authorize(user.id,
                oneclick_user.tbk_user,
                @order.number,
                @order.webpay_amount,
                shares_number,
                @payment.number)

              @response = oneclick_authotize.details

              if oneclick_authotize.details.first['status'] == 'AUTHORIZED' && oneclick_authotize.details.first['response_code'].zero?
                @payment.complete! if !@payment.completed?
                ConfirmPaymentJob.perform_later(@payment.id)

                return true
              else
                @payment.update_column(:response_code, oneclick_authotize.details.first['response_code'].to_s)
                @payment.failure!
                return false
              end
            end

            def oneclick_error(e = nil)
              render json: { success: false, message: "oneclick error #{e.try(:message)}" }
              return
            end
          end
        end
      end
    end
  end
end

app/controllers/spree/checkout_controller_decorator.rb
module Spree::CheckoutControllerDecorator
  def self.prepended(base)
    base.before_action :pay_with_webpay_oneclick_mall, only: :update
  end

  private

  def pay_with_webpay_oneclick_mall
    return unless params[:state] == 'payment'
    return if params[:order].blank? || params[:order][:payments_attributes].blank?

    pm_id = params[:order][:payments_attributes].first[:payment_method_id]
    payment_method = Spree::PaymentMethod.find(pm_id)

    if payment_method && payment_method.kind_of?(Spree::PaymentMethod::WebpayOneclickMall)
      unless @order.user && @order.user.webpay_oneclick_mall_user && @order.user.webpay_oneclick_mall_user.subscribed?
        redirect_to oneclick_mall_subscription_path and return
      end

      oneclick_create_payment(payment_method)
      redirect_to oneclick_mall_pay_path(permitted_params) and return
    end
  end

  def oneclick_create_payment(payment_method)
    payment = @order.payments.build(payment_method_id: payment_method.id, amount: @order.total, state: 'checkout')

    unless payment.save
      flash[:error] = payment.errors.full_messages.join("\n")
      redirect_to checkout_state_path(@order.state) && return
    end

    unless payment.pend!
      flash[:error] = payment.errors.full_messages.join("\n")
      redirect_to checkout_state_path(@order.state) && return
    end
  end

  def permitted_params
    params.permit!
  end
end

Spree::CheckoutController.prepend Spree::CheckoutControllerDecorator

app/controllers/spree/oneclick_mall_payment_controller.rb
module Spree
  class OneclickMallPaymentController < StoreController

    skip_before_action :verify_authenticity_token

    before_action :load_data, only: :pay

    def pay
      unless @order.user && @order.user.webpay_oneclick_mall_user && @order.user.webpay_oneclick_mall_user.subscribed?
        redirect_to oneclick_mall_subscription_path and return
      end

      payment_method = @payment.payment_method
      provider = payment_method.provider.new
      amount  = @order.webpay_amount
      user = @order.user
      oneclick_user = user.webpay_oneclick_mall_user
      shares_number = 1
      oneclick_authotize = provider.authorize(user.id,
                                              oneclick_user.tbk_user,
                                              @order.number,
                                              @order.webpay_amount,
                                              shares_number,
                                              @payment.number)

      if oneclick_authotize.details.first['status'] == 'AUTHORIZED' && oneclick_authotize.details.first['response_code'].zero?
        @payment.complete! if !@payment.completed?
        @order.skip_stock_validation = true

        ix = 0
        while !@order.completed? && ix < 5
          @order.next!
          ix += 1
        end

        redirect_to oneclick_mall_success_path({payment_number: @payment.number}) and return
      else
        @payment.update_column(:response_code, oneclick_authotize.details.first['response_code'].to_s + oneclick_authotize.details.first['status'].to_s)
        @payment.failure!
        redirect_to oneclick_mall_failure_path({payment_number: @payment.number}), alert: I18n.t('payment.transaction_error') and return
      end
    rescue StandardError => e
      oneclick_error(e)
    end

    def success
      @payment = Spree::Payment.find_by!(number: params[:payment_number])
      @order = @payment.order
      session[:order_id] = nil
      @current_order     = nil

      redirect_to root_path and return if @payment.blank?

      if @payment.failed? || !@payment.completed?
        # reviso si el pago esta fallido y lo envio a la vista correcta
        redirect_to oneclick_mall_failure_path(params) and return
      else
        if @order.completed? || @payment.completed?

          unless OneclickNotification.find_by(order_id: @payment.order_id, payment_id: @payment.id)
            flash.notice = Spree.t(:order_processed_successfully)
            flash['order_completed'] = true
          end

          OneclickNotification.create(order_id: @payment.order_id, payment_id: @payment.id)

          redirect_to completion_route and return
        else
          redirect_to oneclick_mall_failure_path(params) and return
        end

      end
    end

    def failure
      @rejected = params[:rejected]=="true"
    end

    def oneclick_error(e = nil)
      flash[:error] = "oneclick error #{e.try(:message)}"
      redirect_to checkout_state_path(@order.state)
      return
    end

    private

    def load_data
      @order = current_order || raise(ActiveRecord::RecordNotFound)
      @payment = @order.payments.order(:id).last
    end

    def completion_route
      spree.order_path(id: @order.number)
    end
  end
end

app/views/spree/oneclick_mall_subscription/subscribe_failure.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="row text-center card my-3 px-4 border p-3">

        <div class="row">
          <div class="col-8 offset-2 col-md-4 offset-md-4">
           <i class="fas fa-exclamation-circle error-text mt-2"></i>
          </div>
          <div class="col-md-12">
            <h4 class="sans-serif my-3">No se pudo realizar la subscripción</h4>
            <p>La subscripción a Oneclick no se pudo realizar en este momento. Reinténtelo y revise la información ingresada.</p>
          </div>
        </div>
        <div class="row">

          <div class="col-12 col-md-10 offset-md-1">
            <div class="row">
              <div class="col-6">
                <%= link_to Spree.t("back"), checkout_state_path(:payment), class: "btn btn-info w-100 btn-outline-primary white" %>
              </div>
              <div class="col-6">
                <%= form_for :subscribe, url: oneclick_mall_subscribe_path do |f| %>
                  <%= f.submit Spree.t("retry"), class: "btn btn-primary w-100" %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/oneclick_mall_subscription/subscribe_success.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="row text-center card my-3 px-4 border p-3">

        <div class="row">
          <div class="col-8 offset-2 col-md-4 offset-md-4">
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player class="webpay-loader" src="https://assets7.lottiefiles.com/private_files/lf30_imtpbtnl.json" background="transparent" speed="1" style="width: 200px; height: 100px;margin: 0 auto;" loop autoplay></lottie-player>
          </div>
          <div class="col-md-12">
            <h4 class="sans-serif my-3">Subscripción exitosa</h4>
            <p>La subscripción a Oneclick resultó exitosa. Ahora puede continuar con el pago.</p>
          </div>
        </div>
        <div class="row">

          <div class="col-12 col-md-10 offset-md-1">
            <div class="row">
              <div class="col-6">
                <%= link_to Spree.t("back"), cookies[:back_url_oneclick], class: "btn btn-info w-100 btn-outline-primary white" %>
              </div>
              <div class="col-6">
                <%= link_to Spree.t("continue_checkout"), checkout_state_path(current_order.state), class: "btn btn-primary w-100" %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/oneclick_mall_subscription/subscription.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="row text-center card my-3 px-4 border p-3">

        <div class="row">
          <div class="col-8 offset-2 col-md-6 offset-md-3">
            <script src="https://unpkg.com/@lottiefiles/lottie-player@latest/dist/lottie-player.js"></script>
            <lottie-player class="webpay-loader" src="https://assets6.lottiefiles.com/packages/lf20_clztx5wi.json" background="transparent" speed="1" style="width: 300px; height: 220px;margin: 0 auto;" loop autoplay></lottie-player>
          </div>
          <div class="col-md-12">
            <h6 class="sans-serif mb-3 mt-0">Te llevaremos a Webpay para agregar tu nueva tarjeta</h6>
            <p style="font-size: .8rem;">Al ingresa los datos se efectuará un cobro de $50 pesos para confirmar tu tarjeta.</p>
            <p style="font-size: .8rem;">Luego regresaremos a Lomi para termminar tu compra.</p>
          </div>
        </div>
        <div class="row">

          <div class="col-12 col-md-10 offset-md-1">
            <div class="row">
              <div class="col-6">
                <%= link_to Spree.t("back"), checkout_state_path(:payment), class: "btn btn-info w-100 btn-outline-primary white" %>
              </div>
              <div class="col-6">
                <%= form_for :subscribe, url: oneclick_mall_subscribe_path do |f| %>
                  <%= f.hidden_field  :back_url, value: request.referer %>
                  <%= f.submit 'Ir a Webpay', class: "btn btn-primary  w-100 " %>
                <% end %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/oneclick_mall_subscription/unsubscribed.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="row text-center card my-3 px-4 border p-3">
        <div class="col-md-12">
          <div class="col-8 offset-2 col-md-4 offset-md-4">
            <i class="fas fa-check-circle success-text mt-2"></i>
          </div>
          <h4 class="sans-serif my-3">Desvinculación exitosa</h4>
          <p>La desvinculación a Webpay Oneclick resultó exitosa.</p>
        </div>
        <div class="col-md-12">
          <%= link_to Spree.t("continue"), cookies[:back_url_oneclick], class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/spree/oneclick_mall_subscription/unsubscription.html.erb
<% if try_spree_current_user && (webpay_oneclick_mall_user = try_spree_current_user.webpay_oneclick_mall_user) && webpay_oneclick_mall_user.subscribed? %>

  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
        <div class="row text-center card my-3 px-4 border p-3">

          <div class="col-8 offset-2 col-md-4 offset-md-4">
            <img class="w-100 lazyload h-auto"
                 data-src="<%= config_img_cdn('oneclick_logo.png', 230, 144) %>" width="230" height="144"
                 alt=""/>
          </div>
          <div class="row">
            <div class="col-md-12">
              <h4 class="sans-serif my-3">Subscripción Activa</h4>
              <p>Tiene una subscripción válida para realizar pagos con Webpay Oneclick:</p>
              <div class="row">
                <div class="col-12 col-md-10 offset-md-1">
                  <dl>
                    <dt><%= Spree.t("oneclick_auth_code") %>:</dt>
                    <dd><%= webpay_oneclick_mall_user.authorization_code %></dd>

                    <dt><%= Spree.t("oneclick_card_type") %>:</dt>
                    <dd><%= webpay_oneclick_mall_user.card_type %></dd>

                    <dt><%= Spree.t("oneclick_card_number") %>:</dt>
                    <dd><%= webpay_oneclick_mall_user.card_number %></dd>

                    <dt><%= Spree.t("oneclick_card_expiration_date") %>:</dt>
                    <dd><%= webpay_oneclick_mall_user.card_expiration_date || "No disponible" %></dd>

                    <dt><%= Spree.t("oneclick_created_at") %>:</dt>
                    <dd><%= l(webpay_oneclick_mall_user.created_at, format: :long) %></dd>
                  </dl>
                </div>
              </div>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <%= link_to Spree.t("oneclick_unsubscribe"), oneclick_mall_unsubscribe_path(back_url: request.referer), class: "btn btn-warning" %>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
<% else %>
  <div class="container">
    <div class="row">
      <div class="col-12 col-md-6 offset-md-3">
        <div class="row text-center card my-3 px-4 border p-3">

          <div class="col-8 offset-2 col-md-4 offset-md-4">
            <img class="w-100 lazyload h-auto"
                 data-src="<%= config_img_cdn('oneclick_logo.png', 230, 144) %>" width="230" height="144"
                 alt=""/>
          </div>
          <div class="col-md-12">
            <h4 class="sans-serif my-3">Subscripción Webpay Oneclick</h4>
            <p class="mb-1">No tiene subscripción activa para realizar pagos con Webpay Oneclick.</p>
            <p><b>Puede registrar una tarjeta en el siguiente link:</b></p>
          </div>
          <div class="col-md-12">
            <%= form_for :subscribe, url: oneclick_mall_subscribe_path do |f| %>
              <%= f.hidden_field  :back_url, value: request.referer %>
              <%= f.submit Spree.t("continue"), class: "btn btn-primary" %>
            <% end %>
          </div>

        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/spree/oneclick_mall_subscription/unsubscription_failure.html.erb
<div class="container">
  <div class="row">
    <div class="col-12 col-md-6 offset-md-3">
      <div class="row text-center card my-3 px-4 border p-3">

        <div class="row">
          <div class="col-8 offset-2 col-md-4 offset-md-4">
            <i class="fas fa-exclamation-circle error-text mt-2"></i>
          </div>
          <div class="col-md-12">
            <h4 class="sans-serif my-3">No se pudo realizar la desvinculación</h4>
            <p>La desvinculación a Webpay Oneclick no se pudo realizar. Intentelo nuevamente en unos minutos.</p>
          </div>
        </div>
        <div class="row">

          <div class="col-12 col-md-8 offset-md-2">
            <div class="row">
              <div class="col-12">
                <%= link_to Spree.t("continue"), account_path, class: "btn btn-primary w-100" %>
              </div>
            </div>
          </div>

        </div>
      </div>
    </div>
  </div>
</div>